"""Add chat_id to marriages

Revision ID: 03925140dc04
Revises:
Create Date: 2026-01-11 01:19:43.945771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03925140dc04'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_loss_records',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['telegram_users.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_roulette_bets_created_at', table_name='roulette_bets')
    op.drop_index('ix_roulette_bets_game_session_id', table_name='roulette_bets')
    op.drop_index('ix_roulette_bets_user_id', table_name='roulette_bets')
    op.drop_table('roulette_bets')
    op.drop_table('users_backup')
    op.drop_table('clan_members')
    op.drop_index('ix_slot_games_created_at', table_name='slot_games')
    op.drop_index('ix_slot_games_user_id', table_name='slot_games')
    op.drop_table('slot_games')
    op.drop_index('ix_basket_games_created_at', table_name='basket_games')
    op.drop_index('ix_basket_games_user_id', table_name='basket_games')
    op.drop_table('basket_games')
    op.drop_index('ix_chat_game_settings_chat_id', table_name='chat_game_settings')
    op.drop_table('chat_game_settings')
    op.drop_index('ix_roulette_games_created_at', table_name='roulette_games')
    op.drop_index('ix_roulette_games_session_id', table_name='roulette_games')
    op.drop_table('roulette_games')
    op.drop_index('ix_admin_logs_admin_id', table_name='admin_logs')
    op.drop_index('ix_admin_logs_created_at', table_name='admin_logs')
    op.drop_table('admin_logs')
    op.drop_index('ix_clans_name', table_name='clans')
    op.drop_table('clans')
    op.drop_table('user_bonuses')
    op.drop_index('ix_donations_status', table_name='donations')
    op.drop_index('ix_donations_user_id', table_name='donations')
    op.drop_table('donations')
    op.drop_index('idx_chat_activity_chat_date', table_name='chat_activity')
    op.drop_table('chat_activity')
    op.drop_table('user_settings')
    op.alter_column('marriages', 'chat_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('roulette_game_logs', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('roulette_transactions', 'game_session_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.create_index(op.f('ix_roulette_transactions_game_session_id'), 'roulette_transactions', ['game_session_id'], unique=False)
    op.add_column('telegram_users', sa.Column('nickname', sa.String(length=32), nullable=True))
    op.add_column('telegram_users', sa.Column('nickname_changed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('telegram_users', 'robberies_today',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('telegram_users', 'action',
               existing_type=postgresql.ENUM('mute', 'ban', 'kick', name='moderation_action'),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('telegram_users', 'duration_minutes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'telegram_users', ['nickname'])
    op.drop_index('ix_transactions_created_at', table_name='transactions')
    op.drop_column('transactions', 'created_at')
    op.alter_column('user_purchases', 'chat_id',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.add_column('users', sa.Column('tg_id', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('chat_id', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('coins', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('win_coins', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('defeat_coins', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('max_win_coins', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('min_win_coins', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('max_bet_coins', sa.Integer(), nullable=True))
    op.drop_index('idx_users_status_text', table_name='users')
    op.drop_index('ix_users_user_id', table_name='users')
    op.create_index(op.f('ix_users_chat_id'), 'users', ['chat_id'], unique=False)
    op.create_index(op.f('ix_users_tg_id'), 'users', ['tg_id'], unique=False)
    op.drop_column('users', 'ban_reason')
    op.drop_column('users', 'has_transfer_limit')
    op.drop_column('users', 'registration_date')
    op.drop_column('users', 'referral_bonus_total')
    op.drop_column('users', 'has_bot_stop_protection')
    op.drop_column('users', 'last_activity')
    op.drop_column('users', 'user_id')
    op.drop_column('users', 'has_robbery_protection')
    op.drop_column('users', 'max_bet')
    op.drop_column('users', 'status_expires')
    op.drop_column('users', 'max_win')
    op.drop_column('users', 'vip_license_count')
    op.drop_column('users', 'max_loss')
    op.drop_column('users', 'is_banned')
    op.drop_column('users', 'license_count')
    op.drop_column('users', 'status_custom_link')
    op.drop_column('users', 'balance')
    op.drop_column('users', 'referrer_id')
    op.drop_column('users', 'wins')
    op.drop_column('users', 'banned_until')
    op.drop_column('users', 'last_daily_bonus')
    op.drop_column('users', 'status')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'referral_count')
    op.drop_column('users', 'status_custom_text')
    op.drop_column('users', 'losses')
    op.drop_column('users', 'has_mute_protection')
    op.drop_column('users', 'last_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('has_mute_protection', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('losses', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('status_custom_text', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('referral_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'regular'::character varying"), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('last_daily_bonus', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('banned_until', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('wins', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('referrer_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('balance', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('status_custom_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('license_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_banned', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('max_loss', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('vip_license_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('max_win', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('status_expires', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('max_bet', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('has_robbery_protection', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('last_activity', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('has_bot_stop_protection', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('referral_bonus_total', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('registration_date', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('has_transfer_limit', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('ban_reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_users_referrer_id', 'users', 'users', ['referrer_id'], ['user_id'])
    op.drop_index(op.f('ix_users_tg_id'), table_name='users')
    op.drop_index(op.f('ix_users_chat_id'), table_name='users')
    op.create_unique_constraint('users_user_id_unique', 'users', ['user_id'])
    op.create_index('ix_users_user_id', 'users', ['user_id'], unique=False)
    op.create_index('idx_users_status_text', 'users', ['status_text'], unique=False)
    op.drop_column('users', 'max_bet_coins')
    op.drop_column('users', 'min_win_coins')
    op.drop_column('users', 'max_win_coins')
    op.drop_column('users', 'defeat_coins')
    op.drop_column('users', 'win_coins')
    op.drop_column('users', 'coins')
    op.drop_column('users', 'chat_id')
    op.drop_column('users', 'tg_id')
    op.alter_column('user_purchases', 'chat_id',
               existing_type=sa.Numeric(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.add_column('transactions', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.create_index('ix_transactions_created_at', 'transactions', ['created_at'], unique=False)
    op.drop_constraint(None, 'telegram_users', type_='unique')
    op.alter_column('telegram_users', 'duration_minutes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('telegram_users', 'action',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('mute', 'ban', 'kick', name='moderation_action'),
               existing_nullable=True)
    op.alter_column('telegram_users', 'robberies_today',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_column('telegram_users', 'nickname_changed_at')
    op.drop_column('telegram_users', 'nickname')
    op.drop_index(op.f('ix_roulette_transactions_game_session_id'), table_name='roulette_transactions')
    op.alter_column('roulette_transactions', 'game_session_id',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('roulette_game_logs', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('marriages', 'chat_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.create_table('user_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(length=10), server_default=sa.text("'ru'::character varying"), autoincrement=False, nullable=True),
    sa.Column('notifications_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('sound_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('auto_repeat_bets', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('auto_double_bets', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('last_roulette_bets', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='fk_user_settings_user_id'),
    sa.PrimaryKeyConstraint('id', name='user_settings_pkey'),
    sa.UniqueConstraint('user_id', name='user_settings_user_id_key')
    )
    op.create_table('chat_activity',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('message_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('messages_count', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='chat_activity_pkey'),
    sa.UniqueConstraint('chat_id', 'user_id', 'message_date', name='chat_activity_chat_id_user_id_message_date_key')
    )
    op.create_index('idx_chat_activity_chat_date', 'chat_activity', ['chat_id', 'message_date'], unique=False)
    op.create_table('donations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('amount_rub', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount_coins', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('payment_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('screenshot_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('screenshot_message_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('is_approved', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('approved_by', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('approved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='fk_donations_user_id'),
    sa.PrimaryKeyConstraint('id', name='donations_pkey')
    )
    op.create_index('ix_donations_user_id', 'donations', ['user_id'], unique=False)
    op.create_index('ix_donations_status', 'donations', ['status'], unique=False)
    op.create_table('user_bonuses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('last_bonus_time', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('bonus_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('last_thief_bonus_time', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('last_police_bonus_time', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('thief_bonus_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('police_bonus_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_bonuses_pkey'),
    sa.UniqueConstraint('telegram_id', name='user_bonuses_telegram_id_key')
    )
    op.create_table('clans',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('clans_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('tag', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('leader_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('deputy_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('total_balance', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('member_count', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('level', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('experience', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('avatar_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('banner_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('color_hex', sa.VARCHAR(length=7), server_default=sa.text("'#000000'::character varying"), autoincrement=False, nullable=True),
    sa.Column('is_open', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('min_balance_to_join', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['deputy_id'], ['users.user_id'], name='fk_clans_deputy_id'),
    sa.ForeignKeyConstraint(['leader_id'], ['users.user_id'], name='fk_clans_leader_id'),
    sa.PrimaryKeyConstraint('id', name='clans_pkey'),
    sa.UniqueConstraint('name', name='clans_name_key'),
    sa.UniqueConstraint('tag', name='clans_tag_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_clans_name', 'clans', ['name'], unique=False)
    op.create_table('admin_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('target_user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.user_id'], name='fk_admin_logs_target_user_id'),
    sa.PrimaryKeyConstraint('id', name='admin_logs_pkey')
    )
    op.create_index('ix_admin_logs_created_at', 'admin_logs', ['created_at'], unique=False)
    op.create_index('ix_admin_logs_admin_id', 'admin_logs', ['admin_id'], unique=False)
    op.create_table('roulette_games',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('result_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('result_color', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('participants_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('total_bets', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('total_wins', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('spin_started', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('spin_ended', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('spin_duration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='roulette_games_pkey'),
    sa.UniqueConstraint('session_id', name='roulette_games_session_id_key')
    )
    op.create_index('ix_roulette_games_session_id', 'roulette_games', ['session_id'], unique=False)
    op.create_index('ix_roulette_games_created_at', 'roulette_games', ['created_at'], unique=False)
    op.create_table('chat_game_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('roulette_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('slot_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('basket_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('min_bet_override', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('max_bet_override', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='chat_game_settings_pkey')
    )
    op.create_index('ix_chat_game_settings_chat_id', 'chat_game_settings', ['chat_id'], unique=False)
    op.create_table('basket_games',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('bet_amount', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('dice_value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('win_amount', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('multiplier', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='fk_basket_games_user_id'),
    sa.PrimaryKeyConstraint('id', name='basket_games_pkey')
    )
    op.create_index('ix_basket_games_user_id', 'basket_games', ['user_id'], unique=False)
    op.create_index('ix_basket_games_created_at', 'basket_games', ['created_at'], unique=False)
    op.create_table('slot_games',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('bet_amount', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('win_amount', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('multiplier', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True),
    sa.Column('win_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='fk_slot_games_user_id'),
    sa.PrimaryKeyConstraint('id', name='slot_games_pkey')
    )
    op.create_index('ix_slot_games_user_id', 'slot_games', ['user_id'], unique=False)
    op.create_index('ix_slot_games_created_at', 'slot_games', ['created_at'], unique=False)
    op.create_table('clan_members',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('clan_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), server_default=sa.text("'member'::character varying"), autoincrement=False, nullable=True),
    sa.Column('joined_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('contributed_amount', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['clan_id'], ['clans.id'], name='fk_clan_members_clan_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='fk_clan_members_user_id'),
    sa.PrimaryKeyConstraint('id', name='clan_members_pkey'),
    sa.UniqueConstraint('user_id', name='clan_members_user_id_key')
    )
    op.create_table('users_backup',
    sa.Column('tg_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('chat_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('coins', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('win_coins', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('defeat_coins', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('roulette_bets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('game_session_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('bet_amount', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('bet_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('bet_value', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('result_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_winner', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('win_amount', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('multiplier', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='fk_roulette_bets_user_id'),
    sa.PrimaryKeyConstraint('id', name='roulette_bets_pkey')
    )
    op.create_index('ix_roulette_bets_user_id', 'roulette_bets', ['user_id'], unique=False)
    op.create_index('ix_roulette_bets_game_session_id', 'roulette_bets', ['game_session_id'], unique=False)
    op.create_index('ix_roulette_bets_created_at', 'roulette_bets', ['created_at'], unique=False)
    op.drop_table('daily_loss_records')
    # ### end Alembic commands ###
